[[redirects]]
  from = "/version-test/api/*"
  to = "https://controle-bc.bubbleapps.io/api/:splat"
  status = 200
  force = true
  [headers]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET,POST,PUT,DELETE,OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"

[[redirects]]
  from = "/*"
  to = "https://controle-bc.bubbleapps.io/:splat"
  status = 200
  force = true
