[[redirects]]
  from = "/api/*"
  to = "https://controle-bc.bubbleapps.io/:splat?:query"  # Substitua pelo seu endpoint real
  status = 200
  force = true

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE"
    Access-Control-Allow-Headers = "Authorization, Content-Type"
