[[redirects]]
  from = "/*"
  to = "https://controle-bc.bubbleapps.io/:splat?:query"  # Adapte conforme seu app Bubble
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}
