# Regras de redirecionamento (proxy)
[[redirects]]
  from = "/api/*"
  to = "https://controle-bc.bubbleapps.io/:splat"
  status = 200
  force = true

# Cabeçalhos (opcional, se precisar definir CORS ou outros)
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "https://tenhopedido.com"
