[[redirects]]
  from = "/api/*"
  to = "https://controle-bc.bubbleapps.io/:splat"  # Adapte conforme seu app Bubble
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}
